### ISSUE TITLE
Fig 2 & Fig 3 

### ISSUE THREAD

**Issue by olixu** [BME-SmartLab/rl-wds#3]
Thanks for your contribution!

How to plot the topology of the water distribution network, for example, the Fig 2 & 3 in your paper? It seems that these two figures in your papers has a high resolution.

**Comment by ghajgato** [comment]
Hello Oliver,

Thank you for reading the paper!

The images of the water distribution networks' topologies were exported as vector graphics from the EPANET GUI, as I recall. The legends were added to them thereafter.

**Comment by olixu** [comment]
> Hello Oliver,
> 
> Thank you for reading the paper!
> 
> The images of the water distribution networks' topologies were exported as vector graphics from the EPANET GUI, as I recall. The legends were added to them thereafter.

Thank you very much!
